// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Athlete struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	Gender     pgtype.Text        `json:"gender"`
	BodyWeight pgtype.Numeric     `json:"body_weight"`
	AvatarUrl  pgtype.Text        `json:"avatar_url"`
	Squat      pgtype.Numeric     `json:"squat"`
	Bench      pgtype.Numeric     `json:"bench"`
	Deadlift   pgtype.Numeric     `json:"deadlift"`
	Total      pgtype.Numeric     `json:"total"`
	Ohp        pgtype.Numeric     `json:"ohp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Bio        pgtype.Text        `json:"bio"`
}

type AthleteBonusLift struct {
	AthleteID        int32          `json:"athlete_id"`
	LiftDefinitionID int32          `json:"lift_definition_id"`
	Value            pgtype.Numeric `json:"value"`
}

type BonusLiftDefinition struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	AthleteID pgtype.Int4        `json:"athlete_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
