// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAthlete = `-- name: CreateAthlete :one
INSERT INTO athletes (name, gender, body_weight, squat, bench, deadlift, total, ohp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio
`

type CreateAthleteParams struct {
	Name       string         `json:"name"`
	Gender     pgtype.Text    `json:"gender"`
	BodyWeight pgtype.Numeric `json:"body_weight"`
	Squat      pgtype.Numeric `json:"squat"`
	Bench      pgtype.Numeric `json:"bench"`
	Deadlift   pgtype.Numeric `json:"deadlift"`
	Total      pgtype.Numeric `json:"total"`
	Ohp        pgtype.Numeric `json:"ohp"`
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (Athlete, error) {
	row := q.db.QueryRow(ctx, createAthlete,
		arg.Name,
		arg.Gender,
		arg.BodyWeight,
		arg.Squat,
		arg.Bench,
		arg.Deadlift,
		arg.Total,
		arg.Ohp,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
	)
	return i, err
}

const createBonusLiftDefinition = `-- name: CreateBonusLiftDefinition :one
INSERT INTO bonus_lift_definitions (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateBonusLiftDefinition(ctx context.Context, name string) (BonusLiftDefinition, error) {
	row := q.db.QueryRow(ctx, createBonusLiftDefinition, name)
	var i BonusLiftDefinition
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, athlete_id)
VALUES ($1, $2, $3)
RETURNING id, username, password, athlete_id, created_at, updated_at
`

type CreateUserParams struct {
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	AthleteID pgtype.Int4 `json:"athlete_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.AthleteID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAthleteBonusLift = `-- name: DeleteAthleteBonusLift :exec
DELETE FROM athlete_bonus_lifts
WHERE athlete_id = $1 AND lift_definition_id = $2
`

type DeleteAthleteBonusLiftParams struct {
	AthleteID        int32 `json:"athlete_id"`
	LiftDefinitionID int32 `json:"lift_definition_id"`
}

func (q *Queries) DeleteAthleteBonusLift(ctx context.Context, arg DeleteAthleteBonusLiftParams) error {
	_, err := q.db.Exec(ctx, deleteAthleteBonusLift, arg.AthleteID, arg.LiftDefinitionID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getAthleteBonusLifts = `-- name: GetAthleteBonusLifts :many
SELECT bld.name, abl.value, bld.id as definition_id
FROM athlete_bonus_lifts abl
JOIN bonus_lift_definitions bld ON abl.lift_definition_id = bld.id
WHERE abl.athlete_id = $1
`

type GetAthleteBonusLiftsRow struct {
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	DefinitionID int32          `json:"definition_id"`
}

func (q *Queries) GetAthleteBonusLifts(ctx context.Context, athleteID int32) ([]GetAthleteBonusLiftsRow, error) {
	rows, err := q.db.Query(ctx, getAthleteBonusLifts, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAthleteBonusLiftsRow{}
	for rows.Next() {
		var i GetAthleteBonusLiftsRow
		if err := rows.Scan(&i.Name, &i.Value, &i.DefinitionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio FROM athletes WHERE id = $1
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRow(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
	)
	return i, err
}

const getBonusLiftDefinitionByName = `-- name: GetBonusLiftDefinitionByName :one
SELECT id, name FROM bonus_lift_definitions WHERE name = $1
`

func (q *Queries) GetBonusLiftDefinitionByName(ctx context.Context, name string) (BonusLiftDefinition, error) {
	row := q.db.QueryRow(ctx, getBonusLiftDefinitionByName, name)
	var i BonusLiftDefinition
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.expires_at, s.created_at, u.username, u.athlete_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetSessionRow struct {
	ID        string             `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	AthleteID pgtype.Int4        `json:"athlete_id"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Username,
		&i.AthleteID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, athlete_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, athlete_id, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAthletes = `-- name: ListAthletes :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio FROM athletes ORDER BY total DESC NULLS LAST
`

func (q *Queries) ListAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesByBonusLift = `-- name: ListAthletesByBonusLift :many
SELECT a.id, a.name, a.gender, a.body_weight, a.avatar_url, a.squat, a.bench, a.deadlift, a.total, a.ohp, a.created_at, a.updated_at, a.bio, abl.value as lift_value, bld.name as lift_name
FROM athletes a
JOIN athlete_bonus_lifts abl ON a.id = abl.athlete_id
JOIN bonus_lift_definitions bld ON abl.lift_definition_id = bld.id
WHERE bld.id = $1
AND (a.gender = $2 OR $2 = '')
ORDER BY abl.value DESC
`

type ListAthletesByBonusLiftParams struct {
	ID     int32       `json:"id"`
	Gender pgtype.Text `json:"gender"`
}

type ListAthletesByBonusLiftRow struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	Gender     pgtype.Text        `json:"gender"`
	BodyWeight pgtype.Numeric     `json:"body_weight"`
	AvatarUrl  pgtype.Text        `json:"avatar_url"`
	Squat      pgtype.Numeric     `json:"squat"`
	Bench      pgtype.Numeric     `json:"bench"`
	Deadlift   pgtype.Numeric     `json:"deadlift"`
	Total      pgtype.Numeric     `json:"total"`
	Ohp        pgtype.Numeric     `json:"ohp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Bio        pgtype.Text        `json:"bio"`
	LiftValue  pgtype.Numeric     `json:"lift_value"`
	LiftName   string             `json:"lift_name"`
}

func (q *Queries) ListAthletesByBonusLift(ctx context.Context, arg ListAthletesByBonusLiftParams) ([]ListAthletesByBonusLiftRow, error) {
	rows, err := q.db.Query(ctx, listAthletesByBonusLift, arg.ID, arg.Gender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAthletesByBonusLiftRow{}
	for rows.Next() {
		var i ListAthletesByBonusLiftRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.LiftValue,
			&i.LiftName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesByGender = `-- name: ListAthletesByGender :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio FROM athletes WHERE gender = $1 ORDER BY total DESC NULLS LAST
`

func (q *Queries) ListAthletesByGender(ctx context.Context, gender pgtype.Text) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesByGender, gender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesSorted = `-- name: ListAthletesSorted :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio FROM athletes
ORDER BY
    CASE WHEN $1::text = 'squat' THEN squat END DESC NULLS LAST,
    CASE WHEN $1::text = 'bench' THEN bench END DESC NULLS LAST,
    CASE WHEN $1::text = 'deadlift' THEN deadlift END DESC NULLS LAST,
    CASE WHEN $1::text = 'ohp' THEN ohp END DESC NULLS LAST,
    CASE WHEN $1::text = 'total' OR $1::text = '' THEN total END DESC NULLS LAST
`

func (q *Queries) ListAthletesSorted(ctx context.Context, sortField string) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesSorted, sortField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesSortedByGender = `-- name: ListAthletesSortedByGender :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio FROM athletes
WHERE gender = $1
ORDER BY
    CASE WHEN $2::text = 'squat' THEN squat END DESC NULLS LAST,
    CASE WHEN $2::text = 'bench' THEN bench END DESC NULLS LAST,
    CASE WHEN $2::text = 'deadlift' THEN deadlift END DESC NULLS LAST,
    CASE WHEN $2::text = 'ohp' THEN ohp END DESC NULLS LAST,
    CASE WHEN $2::text = 'total' OR $2::text = '' THEN total END DESC NULLS LAST
`

type ListAthletesSortedByGenderParams struct {
	Gender    pgtype.Text `json:"gender"`
	SortField string      `json:"sort_field"`
}

func (q *Queries) ListAthletesSortedByGender(ctx context.Context, arg ListAthletesSortedByGenderParams) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesSortedByGender, arg.Gender, arg.SortField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusLiftDefinitions = `-- name: ListBonusLiftDefinitions :many
SELECT id, name FROM bonus_lift_definitions ORDER BY name ASC
`

func (q *Queries) ListBonusLiftDefinitions(ctx context.Context) ([]BonusLiftDefinition, error) {
	rows, err := q.db.Query(ctx, listBonusLiftDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BonusLiftDefinition{}
	for rows.Next() {
		var i BonusLiftDefinition
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :one
UPDATE athletes SET
    name = $2,
    gender = $3,
    body_weight = $4,
    avatar_url = $5,
    bio = $6,
    squat = $7,
    bench = $8,
    deadlift = $9,
    total = $10,
    ohp = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at, bio
`

type UpdateAthleteParams struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Gender     pgtype.Text    `json:"gender"`
	BodyWeight pgtype.Numeric `json:"body_weight"`
	AvatarUrl  pgtype.Text    `json:"avatar_url"`
	Bio        pgtype.Text    `json:"bio"`
	Squat      pgtype.Numeric `json:"squat"`
	Bench      pgtype.Numeric `json:"bench"`
	Deadlift   pgtype.Numeric `json:"deadlift"`
	Total      pgtype.Numeric `json:"total"`
	Ohp        pgtype.Numeric `json:"ohp"`
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) (Athlete, error) {
	row := q.db.QueryRow(ctx, updateAthlete,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.BodyWeight,
		arg.AvatarUrl,
		arg.Bio,
		arg.Squat,
		arg.Bench,
		arg.Deadlift,
		arg.Total,
		arg.Ohp,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
	)
	return i, err
}

const upsertAthleteBonusLift = `-- name: UpsertAthleteBonusLift :exec
INSERT INTO athlete_bonus_lifts (athlete_id, lift_definition_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (athlete_id, lift_definition_id) DO UPDATE SET value = $3
`

type UpsertAthleteBonusLiftParams struct {
	AthleteID        int32          `json:"athlete_id"`
	LiftDefinitionID int32          `json:"lift_definition_id"`
	Value            pgtype.Numeric `json:"value"`
}

func (q *Queries) UpsertAthleteBonusLift(ctx context.Context, arg UpsertAthleteBonusLiftParams) error {
	_, err := q.db.Exec(ctx, upsertAthleteBonusLift, arg.AthleteID, arg.LiftDefinitionID, arg.Value)
	return err
}
