// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAthlete = `-- name: CreateAthlete :one
INSERT INTO athletes (name, gender, body_weight, squat, bench, deadlift, total, ohp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at
`

type CreateAthleteParams struct {
	Name       string         `json:"name"`
	Gender     pgtype.Text    `json:"gender"`
	BodyWeight pgtype.Numeric `json:"body_weight"`
	Squat      pgtype.Numeric `json:"squat"`
	Bench      pgtype.Numeric `json:"bench"`
	Deadlift   pgtype.Numeric `json:"deadlift"`
	Total      pgtype.Numeric `json:"total"`
	Ohp        pgtype.Numeric `json:"ohp"`
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (Athlete, error) {
	row := q.db.QueryRow(ctx, createAthlete,
		arg.Name,
		arg.Gender,
		arg.BodyWeight,
		arg.Squat,
		arg.Bench,
		arg.Deadlift,
		arg.Total,
		arg.Ohp,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, athlete_id)
VALUES ($1, $2, $3)
RETURNING id, username, password, athlete_id, created_at, updated_at
`

type CreateUserParams struct {
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	AthleteID pgtype.Int4 `json:"athlete_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.AthleteID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at FROM athletes WHERE id = $1
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRow(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.expires_at, s.created_at, u.username, u.athlete_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetSessionRow struct {
	ID        string             `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	AthleteID pgtype.Int4        `json:"athlete_id"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Username,
		&i.AthleteID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, athlete_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, athlete_id, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AthleteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAthletes = `-- name: ListAthletes :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at FROM athletes ORDER BY total DESC NULLS LAST
`

func (q *Queries) ListAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesByGender = `-- name: ListAthletesByGender :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at FROM athletes WHERE gender = $1 ORDER BY total DESC NULLS LAST
`

func (q *Queries) ListAthletesByGender(ctx context.Context, gender pgtype.Text) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesByGender, gender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesSorted = `-- name: ListAthletesSorted :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at FROM athletes
ORDER BY
    CASE WHEN $1::text = 'squat' THEN squat END DESC NULLS LAST,
    CASE WHEN $1::text = 'bench' THEN bench END DESC NULLS LAST,
    CASE WHEN $1::text = 'deadlift' THEN deadlift END DESC NULLS LAST,
    CASE WHEN $1::text = 'ohp' THEN ohp END DESC NULLS LAST,
    CASE WHEN $1::text = 'total' OR $1::text = '' THEN total END DESC NULLS LAST
`

func (q *Queries) ListAthletesSorted(ctx context.Context, sortField string) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesSorted, sortField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesSortedByGender = `-- name: ListAthletesSortedByGender :many
SELECT id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at FROM athletes
WHERE gender = $1
ORDER BY
    CASE WHEN $2::text = 'squat' THEN squat END DESC NULLS LAST,
    CASE WHEN $2::text = 'bench' THEN bench END DESC NULLS LAST,
    CASE WHEN $2::text = 'deadlift' THEN deadlift END DESC NULLS LAST,
    CASE WHEN $2::text = 'ohp' THEN ohp END DESC NULLS LAST,
    CASE WHEN $2::text = 'total' OR $2::text = '' THEN total END DESC NULLS LAST
`

type ListAthletesSortedByGenderParams struct {
	Gender    pgtype.Text `json:"gender"`
	SortField string      `json:"sort_field"`
}

func (q *Queries) ListAthletesSortedByGender(ctx context.Context, arg ListAthletesSortedByGenderParams) ([]Athlete, error) {
	rows, err := q.db.Query(ctx, listAthletesSortedByGender, arg.Gender, arg.SortField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Athlete{}
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.BodyWeight,
			&i.AvatarUrl,
			&i.Squat,
			&i.Bench,
			&i.Deadlift,
			&i.Total,
			&i.Ohp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :one
UPDATE athletes SET
    name = $2,
    gender = $3,
    body_weight = $4,
    avatar_url = $5,
    squat = $6,
    bench = $7,
    deadlift = $8,
    total = $9,
    ohp = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, gender, body_weight, avatar_url, squat, bench, deadlift, total, ohp, created_at, updated_at
`

type UpdateAthleteParams struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Gender     pgtype.Text    `json:"gender"`
	BodyWeight pgtype.Numeric `json:"body_weight"`
	AvatarUrl  pgtype.Text    `json:"avatar_url"`
	Squat      pgtype.Numeric `json:"squat"`
	Bench      pgtype.Numeric `json:"bench"`
	Deadlift   pgtype.Numeric `json:"deadlift"`
	Total      pgtype.Numeric `json:"total"`
	Ohp        pgtype.Numeric `json:"ohp"`
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) (Athlete, error) {
	row := q.db.QueryRow(ctx, updateAthlete,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.BodyWeight,
		arg.AvatarUrl,
		arg.Squat,
		arg.Bench,
		arg.Deadlift,
		arg.Total,
		arg.Ohp,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.BodyWeight,
		&i.AvatarUrl,
		&i.Squat,
		&i.Bench,
		&i.Deadlift,
		&i.Total,
		&i.Ohp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
